config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :abouts
  resources :playlists
  resources :mixtapes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/landing'
  root 'pages#landing'

  mount Shrine::DownloadEndpoint => "/attachments"

  get    '/auth/:provider'          => 'omniauth#auth', as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/howto' => 'pages#howto'

  get '/ror' => 'pages#ror'
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
require "image_processing/mini_magick"

class ImageUploader < Shrine
  # Plugins and uploading logic goes here

  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions   # enable Shrine to handle a hash of files
  plugin :delete_raw # delete processed files after uploading

  process(:store) do |io, context|
    original = io.download

    size_800 = resize_to_limit!(original, 561, 462) { |cmd| cmd.auto_orient } # orient rotated images
    size_500 = resize_to_limit(size_800,  500, 250)
    size_300 = resize_to_limit(size_500,  300, 300)
    size_thumbnail = resize_to_limit(size_300, 64, 64)


    { original: io, large: size_800, medium: size_500, small: size_300, thumbnail: size_thumbnail }
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :created_by, class_name: "User"

  def can_user_edit?(user)
    created_by == user
  end

  def can_user_destroy?(user)
    created_by == user
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  # GET /abouts
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  def show
    @about = About.find(params[:id])
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  def create
    @about = About.new(about_params)

    if @about.save
      redirect_to @about, notice: 'About was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /abouts/1
  def update
    @about = About.find(params[:id])
    if @about.update(about_params)
      redirect_to @about, notice: 'About was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /abouts/1
  def destroy
    @about = About.find(params[:id])
    @about.destroy
    redirect_to abouts_url, notice: 'About was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def about_params
    params.fetch(:about, {})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def user_logged_in?
    !!current_user
  end
  helper_method :user_logged_in?

  def authenticate!
    unless logged_in?
      redirect_to auth_path(provider: 'facebook')
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @playlist = Playlist.last
    @playlists = Playlist.all

    @user = User.first
    @users = User.all
  end

  def index
    @page = params[:page].to_i

    @playlists = Playlists.all.order(created_at: :desc).page(@page).per(9)
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  # GET /playlists
  def index
    @playlists = Playlist.where(:created_by_id => current_user)
  end

  # GET /playlists/1
  def show
    @playlist = Playlist.find(params[:id])
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])

    unless @playlist.can_user_edit?(current_user)
      redirect_to root_path, notice: "you can't edit a Mixtape you didn't create"
      return
    end
  end

  # POST /playlists
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.created_by = current_user
    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /playlists/1
  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /playlists/1
  def destroy
    @playlist = Playlist.find(params[:id])

    unless @playlist.can_user_destroy?(current_user)
      redirect_to root_path, notice: "you can't destroy a playlist you didn't create"
      return
    end

    @playlist.destroy
    redirect_to playlists_url, notice: 'Playlist was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def playlist_params
    params.require(:playlist).permit(:embed_link, :image, :mixtape_title)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to auth_path(provider: authentication_data['provider'])
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    flash[:notice] = "Login Failed"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="">
  <title>Jusixo - Mixtape</title>
  <meta name="description" content="Curated Playlists to help fit any mood." />
  <meta name="generator" content="Codeply">

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png?v=2">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png?v=2">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png?v=2">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png?v=2">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png?v=2">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png?v=2">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png?v=2">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png?v=2">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png?v=2">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png?v=2">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=2">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png?v=2">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=2">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png?v=2">
  <meta name="theme-color" content="#ffffff">


  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/howto.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav id="topNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to root_path, class: 'navbar-brand page-scroll' do %>
                <i class="fa fa-play"></i> MIXTAPES
              <% end %>
            </div>
            <div class="navbar-collapse collapse" id="bs-navbar">
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to new_playlist_path, class: 'navbar-brand page-scroll' do %>
                        <i class="fa fa-add"></i> NEW MIXTAPE
                      <% end %>
                    </li>
                    <li>
                        <%= link_to playlists_path, class: 'navbar-brand page-scroll' do %>
                          Your Playlists
                        <% end %>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" data-toggle="modal" title="A free Bootstrap video landing theme" href="#aboutModal">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br>

  <h1 class="text-center">How to post your spotify mix</h1>
    <hr>
    <br>
    <br>
  <h2 class="text-center">Step 1: find your playlist on Spotify and click "Share", then click "Copy Embed Code"</h2>
    <br>
    <div class="how-to-img"><%= image_tag("step1.jpg", class: "img-responsive") %></div>
    <br>
    <br>
  <h2 class="text-center">Step 2: Paste the code into the embed form on the add new mixtape page</h2>
    <br>
    <br>
  <h2 class="text-center">Step 3: delete everything except the embed link inside of the qoutes </h2>
    <div class="col-lg-2 col-sm-2"></div>
    <div class="col-lg-4 col-sm-6"><%= image_tag("2.png", class: "img-responsive") %></div>
    <div class="col-lg-4 col-sm-6"><%= image_tag("3.png", class: "img-responsive") %></div>

    <div class="how-to">
      <h2 class="text-center"> The Embed should look like this before posting</h2>
      <h2><%= image_tag("4.png", class: "img-responsive") %></h2>
    </div>
  </body>
</html>

app/views/pages/landing.html.erb
<!DOCTYPE html>
<html>
  <body>
    <nav id="topNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand page-scroll" href="#first"><i class="fa fa-play"></i> MIXTAPES</a>
            </div>
            <div class="navbar-collapse collapse" id="bs-navbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="page-scroll" href="#second">Tapes</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#last">Contact</a>
                    </li>
                    <li>
                      <%= link_to howto_path do %>How to add your Mixtape<% end %>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <%- if user_logged_in? %>
                   <li>
                     <a>Welcome <%= current_user.name.upcase %></a>
                   </li>
                   <li>
                     <%= link_to "Log Out", logout_path, data: { confirm: 'Are you sure?' } %>
                   </li>
                   <%- else %>
                   <li>
                     <%= link_to auth_path(provider: 'facebook') do %>Sign In<% end %>
                   </li>
                   <% end %>
                  <li>
                      <a class="page-scroll" data-toggle="modal" title="A free Bootstrap video landing theme" href="#aboutModal">About</a>
                  </li>
                </ul>
            </div>
        </div>
    </nav>
    <header id="first">
      <div class="header-content">
        <div class="inner">
            <h1 class="cursive">Jusixo presents Mixtapes</h1>
            <h4>A curated set of playlists to put music to your moods</h4>
            <hr>
            <a href="#second" class="btn btn-primary btn-xl page-scroll">MIXTAPES</a> &nbsp;
            <%= link_to playlists_path, class: 'btn btn-primary btn-xl page-scroll' do %>
              Your Playlists
            <% end %>
        </div>
      </div>
    </header>
    <section id="second" class="no-padding">
        <hr>
        <h1 class="text-center">This website is a fun project I'm working on for me and my friends, to showcase some <a href="ror.html" target="_blank">skills</a> </h1>
        <hr>
        <div class="container-fluid">
          <%= render 'playlists/playlists' %>
        </div>
    </section>

    <section id="last">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="margin-top-0 wow fadeIn">Get in Touch</h2>
                    <hr class="primary">
                    <p>We love feedback. Fill out the form below and I will get back to you as soon as possible.</p>
                </div>
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <form action="https://formspree.io/jusixo@gmail.com" method="POST" class="contact-form row">
                        <div class="col-md-4">
                            <label></label>
                            <input type="text" name="name" class="form-control" placeholder="Name">
                        </div>
                        <div class="col-md-4">
                            <label></label>
                            <input type="email" name="_replyto" class="form-control" placeholder="Email">
                        </div>
                        <div class="col-md-4">
                            <label></label>
                            <input type="tel" name="telNo" class="form-control" placeholder="Phone">
                        </div>
                        <div class="col-md-12">
                            <label></label>
                            <input type="email" name="text" style="height: 100px;" class="form-control" placeholder="Your message here..">
                        </div>
                        <div class="col-md-4 col-md-offset-4">
                            <label></label>
                            <button type="submit" value="Send" data-toggle="modal" data-target="#alertModal" class="btn btn-primary btn-block btn-lg">Send <i class="fa fa-arrow-forward"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <footer id="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-6 col-sm-3 column">
                    <h4>Information</h4>
                    <ul class="list-unstyled">
                      <li><%= link_to abouts_path, target: :_blank do %>Product Information<% end %></li>
                        <li><%= link_to abouts_path, target: :_blank do %>Other Products<% end %></li>
                        <li><%= link_to abouts_path, target: :_blank do %>Costomer Service<% end %></li>
                        <li><%= link_to abouts_path, target: :_blank do %>Developers<% end %></li>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-3 column">
                    <h4>About</h4>
                    <ul class="list-unstyled">
                      <li><%= link_to abouts_path, target: :_blank do %>Contact Us<% end %></li>
                      <li><%= link_to abouts_path, target: :_blank do %>Services<% end %></li>
                      <li><%= link_to abouts_path, target: :_blank do %>Privacy Policy<% end %></li>
                      <li><%= link_to abouts_path, target: :_blank do %>Terms & Conditions<% end %></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-sm-3 column">

                    <h4>Stay Posted</h4>
                    <form action="https://formspree.io/jusixo@gmail.com" method="POST">
                        <div class="form-group">
                          <input type="email" name="_replyto" class="form-control" title="No spam, we promise!" placeholder="Tell us your email">
                        </div>
                        <div class="form-group">
                          <button class="btn btn-primary" type="submit" value="Send" data-toggle="modal" data-target="#alertModal" type="button">Subscribe for updates</button>
                        </div>
                    </form>

                </div>
                <div class="col-xs-1 col-sm-3 text-right">
                    <ul class="list-inline">
                      <br><br><br>
                      <li><a rel="nofollow" href="https://twitter.com/Jusixo" title="Twitter"><i class="icon-lg fa fa-twitter"></i></a>&nbsp;</li>
                      <li><a rel="nofollow" href="https://www.linkedin.com/in/jusixo/" title="Facebook"><i class="icon-lg fa fa-linkedin"></i></a>&nbsp;</li>
                      <li><a rel="nofollow" href="https://www.google.com/search?q=local+pizza+places&oq=local+pizza+pla&aqs=chrome.0.0j69i57j0l4.3756j0j1&sourceid=chrome&ie=UTF-8" title="pizza"><i class="icon-lg fa fa-pie-chart"></i></a></li>
                    </ul>
                </div>
            </div>
            <br/>
            <span class="pull-right text-muted small"><a href="">Mixtapes</a> <%= Time.now.year %></span>
        </div>
    </footer>

    <div id="aboutModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
        	<div class="modal-body">
        		<h2 class="text-center">Mixtapes</h2>
        		<h5 class="text-center">
        		    a free collection of mixtapes curated by me.<br><br>
                This site requires you to have a spotify premium account in order to get the full appreciation<br><br>

        		</h5>
        		<p class="text-justify">
        		  This is just an excersize on some skills while also having a nice looking page to send
              friends to listen to some of my favorite mood music. Eventually i will have a fully functional site that friends of friends and beyond would like to use.
              Thank you for stopping by
        		</p>
        		<p class="text-center"><a href="https://twitter.com/Jusivxo">Contact me on twitter</a></p>
        		<br/>
        		<button class="btn btn-primary btn-lg center-block" data-dismiss="modal" aria-hidden="true"> OK </button>
        	</div>
        </div>
        </div>
    </div>
    <div id="alertModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
        <div class="modal-content">
        	<div class="modal-body">
        		<h2 class="text-center">Thank You!</h2>
        		<p class="text-center" >We will be in touch as soon as possible</p>
        		<p class="text-center"><a href="https://jusixo.github.io/">Learn more about me at Jusixo.github.io</a></p>
        		<br/>
        		<button class="btn btn-primary btn-lg center-block" data-dismiss="modal" aria-hidden="true">OK <i class="fa fa-times-circle-o"></i></button>
        	</div>
        </div>
        </div>
    </div>
  </body>
</html>