config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :abouts
  resources :playlists
  resources :mixtapes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/landing'
  root 'pages#landing'

  mount Shrine::DownloadEndpoint => "/attachments"

  get    '/auth/:provider'          => 'omniauth#auth', as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/howto' => 'pages#howto'

  get '/ror' => 'pages#ror'
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  # GET /subscribers
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  def show
    @subscriber = Subscriber.find(params[:id])
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      redirect_to @subscriber, notice: 'Subscriber was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /subscribers/1
  def update
    @subscriber = Subscriber.find(params[:id])
    if @subscriber.update(subscriber_params)
      redirect_to @subscriber, notice: 'Subscriber was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subscribers/1
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy
    redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def subscriber_params
    params.fetch(:subscriber, {})
  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @subscriber.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h4>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>

<br>


<div class="col-xs-12 col-sm-3 column">
  <%= form_for(@subscriber, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @subscriber.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h4>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Stay Posted</h4>
  <form>
      <div class="form-group">
        <input type="text" class="form-control" title="No spam, we promise!" placeholder="Tell us your email">
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>

        <button class="btn btn-primary" data-toggle="modal" data-target="#alertModal" type="button">Subscribe for updates</button>
      </div>
  </form>
  <% end -%>

</div>

app/views/subscribers/edit.html.erb
<div class="page-header">
  <%= link_to subscribers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @subscriber, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing subscriber</h1>
</div>

<%= render 'form' %>

app/views/subscribers/index.html.erb
<div class="page-header">
  <%= link_to new_subscriber_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Subscriber
  <% end %>
  <h1 Listing>subscribers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @subscribers.each do |subscriber| %>
      <tr>
        <td>
          <%= link_to subscriber do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_subscriber_path(subscriber) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to subscriber, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subscribers/new.html.erb
<div class="page-header">
  <%= link_to subscribers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New subscriber</h1>
</div>

<%= render 'form' %>

app/views/subscribers/show.html.erb
<div class="page-header">
  <%= link_to subscribers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_subscriber_path(@subscriber), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show subscriber</h1>
</div>

<dl class="dl-horizontal">
</dl>