config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :abouts
  resources :playlists
  resources :mixtapes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/landing'
  root 'pages#landing'

  mount Shrine::DownloadEndpoint => "/attachments"

  get    '/auth/:provider'          => 'omniauth#auth', as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/howto' => 'pages#howto'

  get '/ror' => 'pages#ror'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :created_by, class_name: "User"

  def can_user_edit?(user)
    created_by == user
  end

  def can_user_destroy?(user)
    created_by == user
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  # GET /playlists
  def index
    @playlists = Playlist.where(:created_by_id => current_user)
  end

  # GET /playlists/1
  def show
    @playlist = Playlist.find(params[:id])
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])

    unless @playlist.can_user_edit?(current_user)
      redirect_to root_path, notice: "you can't edit a Mixtape you didn't create"
      return
    end
  end

  # POST /playlists
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.created_by = current_user
    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /playlists/1
  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /playlists/1
  def destroy
    @playlist = Playlist.find(params[:id])

    unless @playlist.can_user_destroy?(current_user)
      redirect_to root_path, notice: "you can't destroy a playlist you didn't create"
      return
    end

    @playlist.destroy
    redirect_to playlists_url, notice: 'Playlist was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def playlist_params
    params.require(:playlist).permit(:embed_link, :image, :mixtape_title)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @playlist.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h4>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# embed_link %>
  <div class="container">

  <div class="form-group">
    <%= f.label :mixtape_title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :mixtape_title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :embed_link, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :embed_link, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.hidden_field :image, value: @playlist.cached_image_data %>
      <%= f.file_field :image %>
    </div>
  </div>

  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>
</div>

app/views/playlists/_mixtape.html.erb
<iframe src="<%= @playlist.embed_link %>" width="870" height="500" frameborder="0" allowtransparency="true"></iframe>
<h3>By: <%= @playlist.created_by %></h3>

app/views/playlists/_playlists.html.erb
<%- @playlists.reverse_each do |playlist| %>
  <div class="no-gutter">
    <div class="col-lg-4 col-sm-6">
      <a href="#galleryModal" class="gallery-box center" data-toggle="modal" data-target=".playlist-modal-<%= playlist.id %>">
        <%= image_tag(playlist.image_url(:medium), class: "mixtape_image") unless playlist.image.blank? %>
        <div class="mix-title"><%= playlist.mixtape_title if playlist.mixtape_title %></div>
        <div class="gallery-box-caption">
            <div class="gallery-box-content">
              <div>
                <i class="icon-lg fa fa-play-circle-o"></i>
              </div>
            </div>
        </div>
      </a>
    </div>
  </div>
  <div id="galleryModal" class="modal fade playlist-modal-<%= playlist.id %>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body">
          <iframe src="<%= playlist.embed_link %>" width="870" height="500" frameborder="0" allowtransparency="true"></iframe>
          <br>
          <h4 class="text-right">By: <%= @playlist.created_by.name.upcase %></h4>
          <p>
              <br/>
              <button class="btn btn-primary btn-lg center-block" data-dismiss="modal" aria-hidden="true">Close <i class="fa fa-times-circle-o"></i></button>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<div class="page-header">
  <%= link_to playlists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @playlist, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing playlist</h1>
</div>

<%= render 'form' %>

app/views/playlists/index.html.erb
<div class="page-header">
  <h1 class="text-center">Your Mixtapes</h1>
</div>

<nav id="topNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand page-scroll' do %>
            <i class="fa fa-play"></i> MIXTAPES
          <% end %>
        </div>
        <div class="navbar-collapse collapse" id="bs-navbar">
            <ul class="nav navbar-nav">
                <li>
                  <%= link_to new_playlist_path, class: 'navbar-brand page-scroll' do %>
                    <i class="fa fa-add"></i> NEW MIXTAPE
                  <% end %>
                </li>
                <li>
                  <%= link_to playlists_path, class: 'navbar-brand page-scroll' do %>
                    Your Playlists
                  <% end %>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" data-toggle="modal" title="A free Bootstrap video landing theme" href="#aboutModal">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

    <%- @playlists.reverse_each do |playlist| %>
      <div class="user-mixtapes">

        <ul class="media-list">
          <li class="media">
            <div class="media-left">
              <a href="#">
                <%= image_tag(playlist.image_url(:small), class: "small") unless playlist.image.blank? %>
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= playlist.mixtape_title if playlist.mixtape_title %></h4>
              <%= playlist.embed_link %>
              <br>
              <%- if user_logged_in? %>
                <%= link_to playlist do %>
                  <span class="fa fa-check" aria-hidden="true"></span>
                <% end %>
                <%= link_to edit_playlist_path(playlist) do %>
                  <span class="fa fa-pencil" aria-hidden="true"></span>
                <% end %>
                <%= link_to playlist, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="fa fa-remove" aria-hidden="true"></span>
                <% end %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <% end %>

app/views/playlists/new.html.erb
<div class="page-header">
  <%= link_to playlists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New playlist</h1>
</div>

<%= render 'form' %>

app/views/playlists/show.html.erb
<div class="page-header">
  <%= link_to playlists_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_playlist_path(@playlist), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show playlist</h1>
</div>

<dl class="dl-horizontal">
  <dt>Mixtape Title:</dt>
  <dd><%= @playlist.mixtape_title %></dd>

  <dt>Embed link:</dt>
  <dd><%= @playlist.embed_link %></dd>

  <dt>Image:</dt>
  <%= image_tag(@playlist.image_url(:large), class: "large") unless @playlist.image.blank? %>
</dl>